### ISSUE TITLE
Problems with rotation transform on groups

### ISSUE THREAD

**Issue by skalleAnka** [igagis/svgren#10]
When a group has a rotation transform, the rotation seems to be applied wrong. Here is the actual image:
![test2_real](https://cloud.githubusercontent.com/assets/26508773/24084885/84959f2c-0cf2-11e7-8eb1-802f332de0f2.png)
And here is the rendering:
![test2](https://cloud.githubusercontent.com/assets/26508773/24084887/934c57c2-0cf2-11e7-8c2e-995292927fd5.png)

Here is the SVG file used:
[test2.zip](https://github.com/igagis/svgren/files/853581/test2.zip)

Thanks again for making this, it is great to have a good open-source SVG renderer!

**Comment by igagis** [comment]
Thanks for reporting! I have fixed that, please try **libsvgren** version 0.4.9.
Note: it looks like firefox renders SVG incorrectly in this case, its result is different from Inkscape one. Now **svgren** works as Inkscape.

**Comment by skalleAnka** [comment]
It works now. Thank you so much!
