### ISSUE TITLE
Nuget for svgren on VS2012 results in compilation errors

### ISSUE THREAD

**Issue by darsikiran** [igagis/svgren#11]
I am new to all of these things and wanted to get my hands on SVG rendering and displaying.
I have VS2012 and tried to get svgren and its dependencies using VS2012 Manage Nuget Packages.
When I tried to include the files as described in the example, I run into all sort of issues. Would really appreciate if i can be provided with any pointers...

Here are the errors 

1>------ Build started: Project: MyDiagramTest, Configuration: Debug Win32 ------
1>  StdAfx.cpp
1>  MyDiagram.cpp
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(10): error C2332: 'class' : missing tag name
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(10): error C2011: '<unnamed-tag>' : 'enum' type redefinition
1>          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\shlwapi.h(2278) : see declaration of '<unnamed-tag>'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(10): error C2143: syntax error : missing ',' before '...'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(10): error C2998: 'std::unique_ptr<T> utki::makeUnique' : cannot be a template definition
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(32): error C2332: 'class' : missing tag name
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(32): error C2011: '<unnamed-tag>' : 'enum' type redefinition
1>          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\shlwapi.h(2278) : see declaration of '<unnamed-tag>'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(32): error C2143: syntax error : missing ',' before '...'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(32): error C2065: 'Args' : undeclared identifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(32): error C2988: unrecognizable template declaration/definition
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(32): error C2059: syntax error : '...'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki/Unique.hpp(38): error C2143: syntax error : missing ';' before '}'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(28): error C2146: syntax error : missing ',' before identifier 'noexcept'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(28): error C2065: 'noexcept' : undeclared identifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(31): error C2059: syntax error : ';'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(31): error C2238: unexpected token(s) preceding ';'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(32): error C2059: syntax error : ';'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(32): error C2238: unexpected token(s) preceding ';'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(42): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(53): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(39): error C2780: '_OutTy *std::move(_InIt,_InIt,_OutTy (&)[_OutSize])' : expects 3 arguments - 1 provided
1>          D:\Program Files\vs2012\VC\include\xutility(2556) : see declaration of 'std::move'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(39): error C2780: '_OutIt std::move(_InIt,_InIt,_OutIt)' : expects 3 arguments - 1 provided
1>          D:\Program Files\vs2012\VC\include\xutility(2543) : see declaration of 'std::move'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(39): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) throw()'
1>          With the following template arguments:
1>          'std::function &'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(40): error C2542: 'utki::ScopeExit::f' : class object has no constructor for initialization
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(43): error C2451: conditional expression of type 'std::function' is illegal
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(44): error C2064: term does not evaluate to a function taking 0 arguments
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(54): error C2780: '_OutTy *std::move(_InIt,_InIt,_OutTy (&)[_OutSize])' : expects 3 arguments - 1 provided
1>          D:\Program Files\vs2012\VC\include\xutility(2556) : see declaration of 'std::move'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(54): error C2780: '_OutIt std::move(_InIt,_InIt,_OutIt)' : expects 3 arguments - 1 provided
1>          D:\Program Files\vs2012\VC\include\xutility(2543) : see declaration of 'std::move'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(54): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) throw()'
1>          With the following template arguments:
1>          'std::function &'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(55): error C2678: binary '=' : no operator found which takes a left-hand operand of type 'std::function' (or there is no acceptable conversion)
1>          D:\Program Files\vs2012\VC\include\functional(689): could be 'std::function<_Fty> &std::function<_Fty>::operator =<nullptr>(_Fx &&)'
1>          with
1>          [
1>              _Fx=nullptr
1>          ]
1>          D:\Program Files\vs2012\VC\include\functional(641): or       'std::function<_Fty> &std::function<_Fty>::operator =(const std::function<_Fty> &)'
1>          D:\Program Files\vs2012\VC\include\functional(651): or       'std::function<_Fty> &std::function<_Fty>::operator =(std::function<_Fty> &)'
1>          D:\Program Files\vs2012\VC\include\functional(678): or       'std::function<_Fty> &std::function<_Fty>::operator =(std::function<_Fty> &&)'
1>          D:\Program Files\vs2012\VC\include\functional(704): or       'std::function<_Fty> &std::function<_Fty>::operator =(std::nullptr_t)'
1>          while trying to match the argument list '(std::function, nullptr)'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(55): error C2582: 'operator =' function is unavailable in 'std::function'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(56): error C3536: 'ret': cannot be used before it is initialized
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(56): error C2663: 'std::function<_Fty>::function' : 8 overloads have no legal conversion for 'this' pointer
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(73): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(104): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(119): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(132): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(151): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(164): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(175): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(175): error C2039: 'uint16_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(175): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(192): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(192): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(192): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(193): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(196): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(199): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(202): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(216): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(216): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(216): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(217): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(220): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(223): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(226): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(229): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(232): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(235): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(238): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(252): error C2039: 'uint16_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(252): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(252): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(253): error C2039: 'uint16_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(256): error C2039: 'uint16_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(258): error C2039: 'uint16_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(272): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(272): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(272): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(273): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(276): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(278): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(280): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(282): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(296): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(296): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(296): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(297): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(300): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(302): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(304): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(306): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(308): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(310): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(312): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(314): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(329): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(329): error C2039: 'uint16_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(329): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(346): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(346): error C2039: 'uint32_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(346): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(347): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(349): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(351): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(353): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(367): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(367): error C2039: 'uint64_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(367): error C3646: 'noexcept' : unknown override specifier
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(368): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(370): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(372): error C2039: 'uint8_t' : is not a member of 'std'
1>d:\MyProject\packages\libutki.1.0.32\build\native\include\utki\util.hpp(372): fatal error C1003: error count exceeds 100; stopping compilation

**Comment by igagis** [comment]
Hello, all these errors are expected because **svgren** is coded using C++'11 standard which is supported only starting from VS2015. So, it will not work with VS2012. You can obtain VS2015 Community Edition for free from microsoft website. Recently VS2017 came out and is also available for free, but I did not test it with VS2017 yet. But most likely there will be no issues with VS2017.

So, please use VS2015 or later.
