### ISSUE TITLE
OSX crashes, no longer linked to cairo

### ISSUE THREAD

**Issue by chere005** [igagis/svgren#12]
left a comment on the commit I think is causing this:

https://github.com/igagis/svgren/commit/729eb55565d9200a9dcc651c070c48a4dee9f2ee

**Comment by igagis** [comment]
Thanks for reporting this, I'll have a look now

**Comment by igagis** [comment]
Ok, I added back linking against **cairo**. New version **0.4.12** is available via homebrew now. Please try and let me know if problem is fixed.

**Comment by chere005** [comment]
It is fixed. Thanks a lot!
