### ISSUE TITLE
Background shape is missing

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#14]
Hi,
I haven't had issuses since a quite long time now. Just now I discovered an image where the Background is not drawn. The same image rendered in firefox has the background shape.

Rendered by svgren
![svgren](https://user-images.githubusercontent.com/25054917/27786724-9d794aa0-5fe2-11e7-84d7-cfac7a7223aa.png)

Rendered by firefox
![firefox](https://user-images.githubusercontent.com/25054917/27786742-ba22db26-5fe2-11e7-8c78-8894d6290b3c.png)

I attached the original SVG file.
[FW5-24V.zip](https://github.com/igagis/svgren/files/1119057/FW5-24V.zip)

It would be great if you could fix this.
I'am using the latest versions of your library on Windows with Visual Studio 2015

**Comment by saeitsystems** [comment]
No, the top one is rendered by svgren. The additional text is drawn on top and has nothing to do with the SVG rendering.
The dark background is missing. Instead you can see the green conectors.
![grafik](https://user-images.githubusercontent.com/25054917/27787850-9487f6ea-5fe6-11e7-8d79-8413ca814f66.png)

**Comment by igagis** [comment]
Ah, ok, understood. I'll have a look.

**Comment by saeitsystems** [comment]
Thanks! It would be great if you could fix this.

**Comment by igagis** [comment]
It was a bug in **svgren**, thanks for finding it. It is now fixed, and nuget package **0.4.14** is available, please update.

**Comment by saeitsystems** [comment]
You are very fast!! I'm still struggeling with my linking problems. As soon as I can check your bugfix I'll close the issue. Thanks!!

**Comment by saeitsystems** [comment]
After trying out the bug is fixed - but instead I now got another bug:
![menuebar](https://user-images.githubusercontent.com/25054917/27795252-a76d6faa-6005-11e7-8eb8-f7e2637710f0.jpg)

The symbols which are drawn false
[symbols.zip](https://github.com/igagis/svgren/files/1119681/symbols.zip)

**Comment by igagis** [comment]
This is another issue, I'm already working on it.

**Comment by igagis** [comment]
I prepared the fix, but I have some problems with build system on appveyor.com, so need to resolve those issues to release a new version.

**Comment by igagis** [comment]
Fix ready. Please update to **svgren** version **0.4.17**.

**Comment by saeitsystems** [comment]
After updating to the new version 0.4.17 everything looks great again!! 
Thank you very much for your quick bugfixes and your help with my linking problems!
