### ISSUE TITLE
renderer doesn't support default fill black 

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#2]
Any black element is not rendered correctly. Comparing two svg files shows that with colour black no style element is exported. The file without style renderes correctly in firefox.

SVG-File with error:
[button-add.zip](https://github.com/igagis/svgren/files/698594/button-add.zip)

See screenshot of the compare tool:
![comparison](https://cloud.githubusercontent.com/assets/25054917/21846035/5ee91100-d7f5-11e6-88b2-095feb2bb748.png)

**Comment by igagis** [comment]
Thanks for reporting the issue. I've just fixed it. The new nuget package libsvgren 0.3.22 should be available already, or in about 15 min or so. Let me know if it fixed your problem so that I could close the issue.

**Comment by saeitsystems** [comment]
Thank you very much! That fixed my problem!
I have three other issues/feature requests. I will post them as different issues.
