### ISSUE TITLE
Different rendering after update

### ISSUE THREAD

**Issue by skalleAnka** [igagis/svgren#20]
Hi again :)

After updating to the latest version from 0.4.9 the rendering is different.

Here is what the rendering of an SVG lookes like from Inkscape and in version 0.4.9:
![orig](https://user-images.githubusercontent.com/26508773/28047662-dbdb2048-65eb-11e7-8b50-17cbe780c10b.png)

This is what it looks like now after updating:
![test](https://user-images.githubusercontent.com/26508773/28047675-f3dac2b6-65eb-11e7-88a0-40a12c0532e0.png)

It's the same SVG file I submitted in a previous issue, but here it is again:
[test.zip](https://github.com/igagis/svgren/files/1137523/test.zip)

**Comment by skalleAnka** [comment]
Hmm... I got libsvgdom 0.2.36 from NuGet but I wasn't sure if the latest libsvgren was supposed to use that yet, so i tried 0.2.35 and got this rendering instead: 
![test](https://user-images.githubusercontent.com/26508773/28048089-e793c4d2-65ee-11e7-8a71-65cba1664dcc.png)

Maybe I'm doing something wrong?

**Comment by skalleAnka** [comment]
I just realized after visiting the svgdom page that the latest version is 0.2.39, that's probably what's wrong. I'll have to get all the dependencies and build it manually and try again :)

**Comment by igagis** [comment]
You are trying from Visual Studio, I suppose?
I have some problems with build system on Appveyor.com right now, and it will take some time to fix it, so I cannot release new NuGet packages at the moment, but I will do that as soon as I can. So, for now you can continue using **svgdom** version 0.2.35 and later upgrade to 0.2.39+ when it is available.
Reopening the issue until 0.2.39 is avaialable.

**Comment by igagis** [comment]
Ok, I'll do a workaround for that build system for now as it seems taking too long time.

**Comment by igagis** [comment]
Ok, new packages released to nuget:
**svgdom** version **0.2.40**
**svgren** version **0.4.20**
please try and close the bug.

**Comment by skalleAnka** [comment]
Hi! Thank you for updating. I am now using svgdom 0.2.40 and svgren 0.4.20 from NuGet. I hade a strange setup before where svgren was from github and the dependencies from nuget, but I changed it to use NuGet directly in my project. That should meka it easier to keep it up to date with all the dependencies :)

The sample in the first post is now rendered like this;
![test](https://user-images.githubusercontent.com/26508773/28075323-715071b8-665b-11e7-8015-e188b9416920.png)

The size seems better but there are parts missing. I also have other SVG files that misrender. Should I close this issue and create a new one?

**Comment by igagis** [comment]
No need to close this bug so far, let me still try to reproduce this. You can attach other images which misrender to this bug, but I'd suggest wait a bit, possibly if I fix this problem the others will be fixed too.

**Comment by igagis** [comment]
Ok, I think I reproduced the issue. But it looks like it is only reproduced for Debug configurations. In Release configuration it works OK. Can you confirm the same behavior?

**Comment by skalleAnka** [comment]
I am not able to build release at the moment, that's why I started doing the upgrade dance in the first place :)
I am using Visual Studio 2015 and keep getting 

`1>LINK : fatal error C1900: Il mismatch between 'P1' version '20150812' and 'P2' version '20130802'`

It doesn't really say what file the problem is, but I'm suspecting Cairo and/or Pixman as all the other dependencies seem to have v140 folders now.

But I thought I'd leave that as a later headache for now, as I don't really have a need for release builds at the moment and will upgrade to VS2017 soon and get new problems to sort out anyways ;)

**Comment by igagis** [comment]
Fix ready, please update **svgdom** to version **0.2.41** from NuGet.

**Comment by skalleAnka** [comment]
Yep that did the trick, now all of my SVGs look good again. Thank you so much for your help!
