### ISSUE TITLE
Is the drawing result GPU hardware accelerated?

### ISSUE THREAD

**Issue by trusktr** [igagis/svgren#21]
?

**Comment by igagis** [comment]
No, it is not. Moreover, the library does not display anything on the screen. It only is able to draw the rasterized SVG image to the memory buffer.
The intention of the library is that you first draw the rasterized image of needed size to memory buffer once, then create a texture from it and use that texture with the graphic API you like.

**Comment by trusktr** [comment]
@igagis Thanks for the info. The API that's I'd like is the SVG API, and to animate it, and I'd like it to be accelerated. Thanks!
