### ISSUE TITLE
Some paths elements don't display in rendered image

### ISSUE THREAD

**Issue by skalleAnka** [igagis/svgren#23]
It's me again :) I hope you're not getting too tired of me :O

One of the SVGs I posted in my previous issue has some very small path objects that don't appear on the rendering. When rendered from Inkscape it looks like this:
![test2_inkscape](https://user-images.githubusercontent.com/26508773/28134519-7ff7a2f2-6743-11e7-9802-a2f67cbe13f5.png)

This is the rendering from svgren:
![test](https://user-images.githubusercontent.com/26508773/28134573-a8821004-6743-11e7-87ba-254f3a56498d.png)

I tried to scale up the rendering (see my previous issue ;) to see if the detail would show up, but no luck.

Here is the SVG file again:
[test2.zip](https://github.com/igagis/svgren/files/1142998/test2.zip)

Here's an example of one of the paths that doesn't appear:
`<path
       style="fill:none;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1.00000003pt;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="m 149.375,231.737 c 7.1603,-2.352 14.6432,-5.3254 21.875,-6.875 l -21.875,6.875 c 7.1603,-2.352 14.6432,-5.3254 21.875,-6.875"
       id="path731" />`

**Comment by igagis** [comment]
It's ok, I'm glad to fix if any bugs found.
It is possible that there is something in this path which I haven't implemented yet. But let me check.

**Comment by igagis** [comment]
I made a fix, the problem was that "pt" unit support was not implemented.
Please update **svgdom** to version **0.2.43** via NuGet.

**Comment by skalleAnka** [comment]
Yep, there is detail now. Thank you, you're the best!
