### ISSUE TITLE
<use> element not supported

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [igagis/svgren#24]
The `<use>` element is not being rendered properly. I though that `use` was supported since the code allows element references by id. I tried to render the following example without success:

```
<svg width="80" height="80" xmlns="http://www.w3.org/2000/svg">
  <style>
    .classA {
      fill: red;
    }
  </style> 
  <defs>
    <g id="Port">
      <circle style="fill: inherit;" r="10"/>
    </g>
  </defs>
 
  <text y="15">black</text>
  <use x="50" y="10" href="#Port" />
  <text y="35">red</text>
  <use x="50" y="30" href="#Port" class="classA"/>
  <text y="55">blue</text>
  <use x="50" y="50" href="#Port" style="fill: blue;"/>
</svg>
```

It should look something like this:

<img width="80" alt="screen shot 2017-07-20 at 8 56 49 am" src="https://user-images.githubusercontent.com/5825034/28426941-89fe4bf2-6d29-11e7-8f8a-f06f060eee44.png">

This is what I get instead:

![out](https://user-images.githubusercontent.com/5825034/28427335-bb6e429a-6d2a-11e7-821c-614460a245b2.png)

**Comment by igagis** [comment]
Thanks for reporting this! I'll have a look next week. I'm currently on a trip without access to the computer.

**Comment by igagis** [comment]
I think 'use' support can be implemented and I will start working on it next week. But support of 'text', which is also present in your example,  is not planned in the near future, because it is too complex and will require storing fonts somewhere.

**Comment by JaimeIvanCervantes** [comment]
Ok! By now I'm somewhat familiar with your library and I might have some time to help you next week so let me know ;)

**Comment by igagis** [comment]
@JaimeIvanCervantes 
Ok, finally, the <use> element is now supported in **svgdom 0.2.49** and **svgren 0.4.23**.
But your example also uses the <styles> element which is not supported yet.

**Comment by JaimeIvanCervantes** [comment]
Excellent, thanks! I'll open the new issue about `<style>` support.

Also, for text and truetype font  support, I believe `nanosvg` is borrowing some ideas from an stb header only library called `stb_truetype`: https://github.com/nothings/stb

Maybe I could also look into basic text support.

**Comment by igagis** [comment]
I am doing some refactoring right now, moving stuff to different files...

Regarding the truetype, I think it is not a problem to use `freetype`, the other thing is that along with SVG file one will have to supply the fonts also to render the image, so it will be more clumsy. For now I consider it is simpler to just convert text to geometry in your favourite SVG editor and live with it :).
But I'm open to consider proposals regarding text support if any.
