### ISSUE TITLE
Librariy dependency for svgren is not up to date

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#30]
Trying to link svgren (min version from NuGet Package is 0.2.35) with svgdom library version 0.2.58 creates a few link errors:
`
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::PathElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUPathElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::PathElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUPathElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::RectElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABURectElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::RectElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABURectElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::CircleElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUCircleElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::CircleElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUCircleElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::EllipseElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUEllipseElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::EllipseElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUEllipseElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::LineElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABULineElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::LineElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABULineElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::PolylineElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUPolylineElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::PolylineElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUPolylineElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::PolygonElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUPolygonElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::PolygonElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUPolygonElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::GElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUGElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::GElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUGElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::SvgElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUSvgElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::SvgElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUSvgElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::SymbolElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUSymbolElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::SymbolElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUSymbolElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::UseElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUUseElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::UseElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUUseElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::DefsElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUDefsElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::DefsElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUDefsElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::Gradient::StopElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUStopElement@Gradient@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::Gradient::StopElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUStopElement@Gradient@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::LinearGradientElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABULinearGradientElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::LinearGradientElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABULinearGradientElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::RadialGradientElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABURadialGradientElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::RadialGradientElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABURadialGradientElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::FilterElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUFilterElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::FilterElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUFilterElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::FeGaussianBlurElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUFeGaussianBlurElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::FeGaussianBlurElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUFeGaussianBlurElement@2@@Z)
libsvgren.lib(render.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::ImageElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUImageElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall svgdom::ConstVisitor::visit(struct svgdom::ImageElement const &)" (?visit@ConstVisitor@svgdom@@UAEXABUImageElement@2@@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "public: class std::array<float,2> __thiscall svgdom::FeGaussianBlurElement::getStdDeviation(void)const " (?getStdDeviation@FeGaussianBlurElement@svgdom@@QBE?AV?$array@M$01@std@@XZ) referenced in function "public: virtual void __thiscall `private: void __thiscall svgren::Renderer::applyFilter(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)'::`2'::FilterApplyer::visit(struct svgdom::FeGaussianBlurElement const &)" (?visit@FilterApplyer@?1??applyFilter@Renderer@svgren@@AAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@UAEXABUFeGaussianBlurElement@svgdom@@@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "protected: void __thiscall svgdom::ConstVisitor::relayAccept(struct svgdom::Container const &)" (?relayAccept@ConstVisitor@svgdom@@IAEXABUContainer@2@@Z) referenced in function "public: void __thiscall svgren::Renderer::relayAccept(struct svgdom::Container const &)" (?relayAccept@Renderer@svgren@@QAEXABUContainer@svgdom@@@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "public: struct svgdom::StyleValue const * __thiscall svgdom::StyleStack::getStyleProperty(enum svgdom::StyleProperty_e)const " (?getStyleProperty@StyleStack@svgdom@@QBEPBUStyleValue@2@W4StyleProperty_e@2@@Z) referenced in function "public: __thiscall svgren::Renderer::SetTempCairoContext::SetTempCairoContext(class svgren::Renderer &)" (??0SetTempCairoContext@Renderer@svgren@@QAE@AAV12@@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "public: __thiscall svgdom::StyleStack::Push::Push(class svgdom::StyleStack &,struct svgdom::Styleable const &)" (??0Push@StyleStack@svgdom@@QAE@AAV12@ABUStyleable@2@@Z) referenced in function "private: void __thiscall svgren::Renderer::renderSvgElement(struct svgdom::SvgElement const &,struct svgdom::Length const &,struct svgdom::Length const &)" (?renderSvgElement@Renderer@svgren@@AAEXABUSvgElement@svgdom@@ABULength@4@1@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "public: __thiscall svgdom::StyleStack::Push::~Push(void)" (??1Push@StyleStack@svgdom@@QAE@XZ) referenced in function "private: void __thiscall svgren::Renderer::renderSvgElement(struct svgdom::SvgElement const &,struct svgdom::Length const &,struct svgdom::Length const &)" (?renderSvgElement@Renderer@svgren@@AAEXABUSvgElement@svgdom@@ABULength@4@1@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "public: __thiscall svgdom::Finder::Finder(struct svgdom::Element const &)" (??0Finder@svgdom@@QAE@ABUElement@1@@Z) referenced in function "public: __thiscall svgren::Renderer::Renderer(struct _cairo *,float,class std::array<float,2>,struct svgdom::SvgElement const &)" (??0Renderer@svgren@@QAE@PAU_cairo@@MV?$array@M$01@std@@ABUSvgElement@svgdom@@@Z)
libsvgren.lib(Renderer.obj) : error LNK2019: unresolved external symbol "public: struct svgdom::Finder::ElementInfo const * __thiscall svgdom::Finder::findById(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?findById@Finder@svgdom@@QBEPBUElementInfo@12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "private: void __thiscall svgren::Renderer::setGradient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?setGradient@Renderer@svgren@@AAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)

`

**Comment by igagis** [comment]
Please use always latest versions of both libraries. These two are probably binary incompatible

**Comment by igagis** [comment]
yes, I will update the library dependency version at some point, but as now the libs are under development the dependency versions are not updated regularly

**Comment by saeitsystems** [comment]
Ok, I just tried to be clever unsing an older version of svgdom to avoid the assertion.
I will try the new 0.2.71 version of svgdom now.
