### ISSUE TITLE
SVG Animation support

### ISSUE THREAD

**Issue by isaactzab** [igagis/svgren#31]
I just know if supports svg animation and export from specific frame. This is a cool feature.

**Comment by igagis** [comment]
Would be great if you provide some SVG sample files with animation

**Comment by isaactzab** [comment]
Of course. This is a very simple animation following w3 standard.
Here a link about animations:
https://www.w3.org/TR/SVG/animate.html#AnimateElement

I'm not an experienced programmer, but I'd like to help.

`<svg xmlns="http://www.w3.org/2000/svg">
  <rect height="100%" width="100%" fill="#fff"/>
  <g stroke="#000">
    <g fill="none" stroke-width="2">
      <animateTransform attributeName="transform" type="rotate" dur="5s" from="360 100 100" to="0 100 100" repeatCount="indefinite"/>
      <ellipse cx="100" cy="100" rx="75" ry="75"/>
      <path stroke="#636363" stroke-width="6" d="M100 100L45 45"/>
    </g>
    <path stroke="red" stroke-width="6" d="M100 175v25"/>
  </g>
</svg>
`

**Comment by igagis** [comment]
Thanks! I will look into it.

**Comment by isaactzab** [comment]
This website has some svg animation examples

http://srufaculty.sru.edu/david.dailey/svg/bucketful.htm

**Comment by igagis** [comment]
Animation is not planned to be supported
