### ISSUE TITLE
update to svgdom 0.3.4

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#33]
While svgdom 0.3.4 has support for 'enable-background' property and some additional filter elements too, it would be nice if svgren could use them.
In the attached image you can see at least one problem spot.
![capture](https://user-images.githubusercontent.com/1651549/30431873-a50b1c0c-9968-11e7-9110-8562019fcc1d.PNG)

**Comment by igagis** [comment]
Finally, it is fixed in **svgren** version **0.4.42**
