### ISSUE TITLE
Render bugs

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#34]
Hi there!
Still enjoying this excellent library )
But it's time to notice that our stylish sport car has some significant render artifacts on the hood and bumpers.
I suppose they appear due to a bug, because as far as I can remember, about a month ago the car had no those problems. Certainly, it had other ones but the specular spots on the hood were a bit more soft. They had no such sharp edges.
Hope you can fix it easily.

![car_from_test](https://user-images.githubusercontent.com/1651549/30546070-3b28e65a-9c94-11e7-82c3-f9c1c8bc2e29.png)

**Comment by igagis** [comment]
Thanks for reporting, I'll have a look.

**Comment by igagis** [comment]
The second and fourth arrows from the left point to normal rendering. It appears here becausethe image is not actually blended with black background in this test application, i.e. the alpha-channel is ignored.

**Comment by igagis** [comment]
Fixed in **svgdom 0.3.6** and **svgren 0.4.41**

https://travis-ci.org/igagis/svgren/builds/277317863
https://ci.appveyor.com/project/igagis/svgren/build/master-422

**Comment by Papirosnik** [comment]
thanks, it is rendered properly now.
