### ISSUE TITLE
svgdom 0.3.6

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#38]
Hi there!
I've noticed that despite existing svgdom version 0.3.6 you're still using 0.3.3 in your ms vs  projects: libsvgren and render_test (see corresponding packages.config for each projects). Is it ok?

**Comment by igagis** [comment]
Hi!

well, it is kind of OK. When the project is built on Appveyor it does `nuget update` first, so those are updated to latest versions there.
Updating those by hand every time is too time consuming, and those are projects for debugging purposes anyway.

Does this affect somehow your work? If so I can update to latest versions by request.

**Comment by Papirosnik** [comment]
Nope, it doesn't affect and I'm able to change it manually.
Just was wondering, what is the reason to use 0.3.3 while more newer version exists.
Thanks!
