### ISSUE TITLE
I don't need swap Red and Blue

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#4]
In my case I create a mfc Bitmap with transparency from the rendered bytes. I found ot that I need to swap red and blue to get the correct colors. When I looked at the source code of the renderer method I found out that swap of red and blue is done in the renderer method as well.
In my case I wouldn't need the internal swap of red & blu at all. Now I need to to do it a second time to revert the internal swap.
Perhaps an aditional parameter of the renderer method could save the double swap times.

**Comment by igagis** [comment]
Fix implemented, will be available in version 0.4.0

**Comment by igagis** [comment]
I added the new parameter to render() function in version 0.4.0. The nuget package should be out shortly.

**Comment by saeitsystems** [comment]
I have tested your changes. Works great now without double swap.
