### ISSUE TITLE
Masked images are not rendered correctly

### ISSUE THREAD

**Issue by MobileSam** [igagis/svgren#40]
I have an SVG that looks like this:
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="57.12901" height="57.53997" viewBox="0 0 57.12901 57.53997">
    <defs>
        <mask id="mask">
            <circle cy="37.45" cx="36.972" r="28.563" fill="#ffffff" transform="translate(-8.40599 -8.47303)"/>
            <path d="M28.616 28.17h.8c5.4 0 6.84-2.8 6.96-4.92h4.6v28.4h-5.6V32.09h-6.76v-3.92z" fill="#000000" transform="translate(-8.40599 -8.47303)"/>
        </mask>
    </defs>

    <rect width="100%" height="100%" mask="url(#mask)"/>
</svg>
```

but once it renders, I only get a black rectangle? It seems like the mask is ignored completely.

**Comment by igagis** [comment]
Thanks for reporting it. Masking is not implemented yet. I'll try to implement it soon.

**Comment by igagis** [comment]
The masking is implemented in **svgren** version **0.4.45**. I could render the example svg from original post.

Please verify and close the issue if it works for you. Thanks.

**Comment by MobileSam** [comment]
It's working great with all the images we had.
Thanks!

**Comment by igagis** [comment]
Glad to hear :)
