### ISSUE TITLE
wrong processing

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#46]
Hi there!
I've got a svg that can't be rendered correctly.
It's pretty simple, could you take a quick glance at it?
Thx

[testgrad.svg.zip](https://github.com/igagis/svgren/files/1685938/testgrad.svg.zip)

**Comment by igagis** [comment]
Fixed in **svgren** version **0.4.47**

**Comment by Papirosnik** [comment]
thank for the fix
