### ISSUE TITLE
style "visibility:hidden" of GElement not working as intended, only style "opacity:0" does

### ISSUE THREAD

**Issue by xamidi** [igagis/svgren#49]
I created a svg with a \<g\> working as a library, so I can \<use\> its elements multiple times elsewhere. But hiding that library did not work using style="visibility:hidden".
I came across https://stackoverflow.com/a/20328945/3410351, so I tried style="opacity:0" and it actually hides the children of the GElement. However, those SVGs with \<g style="visibility:hidden"\> are not rendered correctly by SvgRen.

**Comment by igagis** [comment]
fixed in **svgren** version **0.4.48**
