### ISSUE TITLE
Initial white or black transparent surface makes a difference

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#5]
In my case I render SVG images which are not fully trancparent in some parts. These images are draw in my mfc application onto other images/backgrounds.
I found ot that it makes a difference if I fill the background with 0x00000000 or 0x00FFFFFF.
I got the best results with a transparent grey background of 0x00AFAFAF.
It would help me a lot to have the filling colour as parameter (with default argument) of the renderer method.
For now I have modified the original source to fix my Problem:

```
	for(auto& c : ret){
// #ifdef M_SVGREN_WHITE_BACKGROUND
// 		c = 0xffffffff;
// #else
// 		c = 0;
// #endif
		c = 0x00AFAFAF;
	}

```
This would also help to get rid of the M_SVGREN_WHITE_BACKGROUND define.

**Comment by igagis** [comment]
Do you draw the resulting image to your other images/backgrounds using any alpha blending?
Could you give example screen shots of your results with different background fillings?

**Comment by saeitsystems** [comment]
Her is an Example with the two different extreme colours black-transparent and white-transparent.
I draw a green hover image onto the already rendered image. I also attached the green hover rechtangle.
![background_0x00ffffff](https://cloud.githubusercontent.com/assets/25054917/21885131/9e213ac0-d8b6-11e6-8b40-c10ebfc25e26.png)
![background_0x00000000](https://cloud.githubusercontent.com/assets/25054917/21885134/a18e0274-d8b6-11e6-831c-f1895f8a7b32.png)
[HoverFW10_big.zip](https://github.com/igagis/svgren/files/701288/HoverFW10_big.zip)

**Comment by igagis** [comment]
So, as I understand, you draw this Green frame image to black/white background first and then draw the raster image on top of other stuff, right?
The result will also depend on blending method you use when drawing the raster image. Which one do you use? Like srcColor * Alpha + dstColor * (1 - Alpha) ?
If you need initial white background you can add a lower-layered white rectangle right into your svg, it will give the same result as your modifications to the code.

Could you describe which effect are you trying to achieve?

**Comment by saeitsystems** [comment]
For all the internal pixel images I use the cXimage class for drawing [http://www.xdp.it/cximage.htm](url)
I will have a look if I can change the transparent drawing  method. The effect I want to archive is a hover area with a green frame and green transparent shine like green glass. But where from is the difference you can see in the above pictures? The color is the green from the border but comes out different depending on the fully transparent background color.

**Comment by igagis** [comment]
Which method of cXimage do you use to actually draw it to screen?

**Comment by saeitsystems** [comment]
This one:
`long	Draw(HDC hdc, long x=0, long y=0, long cx = -1, long cy = -1, RECT* pClipRect = 0, bool bSmooth = false);
`
With hdc and Position x and y. All the other parameters are the default parameters

**Comment by igagis** [comment]
I checked the source code and it looks like they use `srcColor * Alpha + dstColor * (1 - Alpha)` alpha blending. In this case black transparent background should be okay. Actually, the second image which you attached is the effect you want, it's like a green glass, isn't it? The first one is not like a glass because it actually makes the resulting image lighter than it is, and any gray background will make it only lighter, but real glass does not make things lighter. Anyway, if you need some other background then just insert the rectangle of needed color to the SVG file. I don't think that **svgren** has to be modified in this matter.

It looks strange though that you get different results with different initial filling but with zero alpha in both cases...

**Comment by saeitsystems** [comment]
> It looks strange though that you get different results with different initial filling but with zero alpha in both cases...

That is what I think. 
I already tried transparent backdround shapes with different colors but that doesn't make a difference.
The second image looks better but I would prefer a slightly lighter green. Therfor my favorite background is 0x00AFAFAF.
A default parameter would give me the chance to use svgren without modifikation, and any other user could chose between white or black transparent background.

**Comment by igagis** [comment]
As I said, you can achieve the same without modification of **svgren** by just adding the background rectangle to the SVG file itself. But basically it basically means that you need to adjust your transparent green color.

Also, you can refer to https://www.cairographics.org/operators/ and see there `CAIRO_OPERATOR_OVER` to understand what's actually happening to understand which color you need to select to achieve desired effect.

**Comment by saeitsystems** [comment]
I tried to render the transparent area with the green from the hover area as background and that is the best result for me.
I would realy love to have the initial fill background as parameter at least as static variable in the namespace so that I am able to modify the color to my needs.
![background_0x00_green_](https://cloud.githubusercontent.com/assets/25054917/21924008/68450b54-d977-11e6-8d3e-9d436dc032e9.png)
.

**Comment by igagis** [comment]
I still think that you are doing something wrong, or cxImage class does wrong alpha blending.
I tried your SVG in my program and it works correctly, giving the exact result that you want, see the screenshot. So, it should work OK with black transparent initial background.

![screenshot_2017-01-13_13-29-50](https://cloud.githubusercontent.com/assets/783401/21928584/67165a0e-d994-11e6-809a-c0e2df167fcb.png)

Is there any chance I could try your code on my computer?

**Comment by saeitsystems** [comment]
The resulting image is different depending on the initial fully transparent fill colour. What is the reason for the difference? It is not cXimage because the only thing I change is the startup fill colour with alpha zero.
I think when cairo renders a semi transparent shape it does something with the background colour found even if this is a fully transparent background.
I bet you get a difference (compare the resulting pixel vector) if you render the same image with two different full transparent startup backgrounds. 
But you can already see it from my three examples - see above.
Probably if you initialise your shape with the real background (in my example the station image) you get a perfect result.

**Comment by igagis** [comment]
I think I found the cause of the uncertainities, it's because cairo uses pre-multiplied alpha. This is why you get different result with different initial filling. Anyway, the end result is not quite what user would expect, so need to come up with some solution. In the **svgren** output image the alpha shall be non-premultiplied, so, need to fix that somehow

**Comment by saeitsystems** [comment]
That sounds plausible. Tell me if you found a solution

**Comment by igagis** [comment]
Ok, I made a fix, **libsvgren** version 0.4.2 is out. Please verify

**Comment by saeitsystems** [comment]
I just had a look at your fix:

```
	for(auto &c : ret){
		std::uint32_t a = (c >> 24);
		std::uint32_t r = (c & 0xff) * 0xff / a;
		std::uint32_t g = ((c >> 8) & 0xff) * 0xff / a;
		std::uint32_t b = ((c >> 16) & 0xff) * 0xff / a;
		c = ((a << 24) | (b << 16) | (g << 8) | r);
	}

```

What happens when alpha is 0??

**Comment by saeitsystems** [comment]
My sugestion:

```
	//unpremultiply alpha
	for (auto &c : ret) {

		std::uint32_t a = (c >> 24);

		if (a > 0)
		{
			std::uint32_t r = (c & 0xff);
			std::uint32_t g = ((c >> 8) & 0xff);
			std::uint32_t b = ((c >> 16) & 0xff);

			r <<= 8;
			g <<= 8;
			b <<= 8;
			r /= a;
			g /= a;
			b /= a;

			c = ((a << 24) | (b << 16) | (g << 8) | r);
		}
	}

```

**Comment by saeitsystems** [comment]
The transparent parts look ok now but bright colors are getting false. I think the code shoud be reduced to semitransparent parts only.
![2017-01-05 13_22_42-clipboard](https://cloud.githubusercontent.com/assets/25054917/21933540/1f32c33c-d9a6-11e6-9039-91815059215a.png)
![bright-colors](https://cloud.githubusercontent.com/assets/25054917/21933572/3357d550-d9a6-11e6-8b4c-f2bd632c0377.png)

**Comment by igagis** [comment]
Nice catch with division by zero, I fixed that also, version 0.4.3 is out. I prefer readability of the code, so I rely on optimizer to substitute multiplication by 0xff to 8 bit right shift. Please try.
What's wrong with bright colors on that picture?

**Comment by saeitsystems** [comment]
It's supposed to be like this:
![korrectcolours](https://cloud.githubusercontent.com/assets/25054917/21933811/31488948-d9a7-11e6-9eb1-13085dda1187.png)

**Comment by saeitsystems** [comment]
Anyway this operation is unnessesary if there is no transparency at all! And if alpha is 1 too.

**Comment by igagis** [comment]
could you attach your SVG icon with this yellow background and green and blue labels?

**Comment by saeitsystems** [comment]
But the above Image with the condition  if ( (a > 1) && (a < 255) )
creates a green shadow for the folder icon which is not correct

**Comment by saeitsystems** [comment]
Here you are ....
[pp-list.zip](https://github.com/igagis/svgren/files/704559/pp-list.zip)

**Comment by igagis** [comment]
Ok, version 0.4.4 is out, please try

**Comment by saeitsystems** [comment]
The Result seems to be pefect now. I would like to sugesst a smal optimization:
		if (a != 0 && a != 0xff ) {

because most pixel are transparent or not and all the calculation is not needed in these two cases.

![perfect](https://cloud.githubusercontent.com/assets/25054917/21934736/dc6b5c80-d9aa-11e6-8920-935483549b31.png)
![verygood1](https://cloud.githubusercontent.com/assets/25054917/21934739/de5d4abc-d9aa-11e6-8594-9be8ec2b0b6b.png)

**Comment by igagis** [comment]
I did the optimization, and version 0.4.5 should be out soon, like in 10 minutes.
Please test it and close the issue if it works.
And thanks for reporting the problems, it helps to make the library better! Would be nice if you give a star to the project here on github.

**Comment by saeitsystems** [comment]
I mean:

```

	//unpremultiply alpha
	for (auto &c : ret) {
		std::uint32_t a = (c >> 24);
		if (a != 0 ) {
			if (a != 0xff) {
				std::uint32_t r = (c & 0xff) * 0xff / a;
				utki::clampTop(r, std::uint32_t(0xff));
				std::uint32_t g = ((c >> 8) & 0xff) * 0xff / a;
				utki::clampTop(g, std::uint32_t(0xff));
				std::uint32_t b = ((c >> 16) & 0xff) * 0xff / a;
				utki::clampTop(b, std::uint32_t(0xff));
				c = ((a << 24) | (b << 16) | (g << 8) | r);
			}
		}
		else {
			c = 0;
		}
	}


```

**Comment by igagis** [comment]
yep, see above

**Comment by saeitsystems** [comment]
I would give you 5 stars if possible. This is the only easy to use and open source SVG solution for VS2015 I found on the internet! And your help was great!

**Comment by igagis** [comment]
Thanks!
