### ISSUE TITLE
Error in renderer gradientGetFx

### ISSUE THREAD

**Issue by VilleKrumlinde** [igagis/svgren#52]
Hi, thanks for this library.

I found an issue with a svg file that causes crash in gradientGetFx method.

It seems "caster.radial" is not null so it passes the if-test but then radial points to deallocated memory so it crashes. 

I cannot share the svg-file here but I can email it if you want.

**Comment by igagis** [comment]
@VilleKrumlinde I will certainly need the SVG which reproduces the problem. Please send it to me _igagis@gmail.com_
I will not publish it anywhere.

**Comment by VilleKrumlinde** [comment]
@igagis Thanks, email sent.

**Comment by VilleKrumlinde** [comment]
@igagis OK, image sent how it looks like in InkScape.

**Comment by igagis** [comment]
All is fixed in **svgren** version **0.4.49** and **svgdom** version **0.3.17**

**Comment by VilleKrumlinde** [comment]
@igagis I can confirm it is working perfectly now. Thank you very much!
