### ISSUE TITLE
Wrong color of the shape

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#55]
Hi there!
I've bumped into this svg which being rendered via svgren gives different result compared to  browsers and inkscapes. Everywhere the color of the main shape is blue, in svgren it's greenish.
[dropshadowfilter.svg.zip](https://github.com/igagis/svgren/files/2053458/dropshadowfilter.svg.zip)

**Comment by igagis** [comment]
Ok, fix is ready and available in **svgren** version **0.4.53**
