### ISSUE TITLE
crash on certain svgs

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#56]
Hi there!
Still enjoying your library,
got a couple of troubled svgs.
[svgs.zip](https://github.com/igagis/svgren/files/2136322/svgs.zip)

**Comment by igagis** [comment]
The root cause of this is same as #51 , so it is a duplicate bug.
I will try to find a way to workaround this problem...

**Comment by igagis** [comment]
I implemented some workaround in version **0.4.54**. These images seem to work. Not sure about all other possible ones.

**Comment by Papirosnik** [comment]
workaround does work
