### ISSUE TITLE
vector iterator not dereferencable

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#57]
I'm getting this exception on the attached svg.
[0.451.svg.zip](https://github.com/igagis/svgren/files/2196851/0.451.svg.zip)

**Comment by igagis** [comment]
@Papirosnik 
which **svgren** version do you use?
Do you get this on Android? I could not reproduce on Linux so far...

**Comment by igagis** [comment]
Reproduced on Windows, will investigate

**Comment by Papirosnik** [comment]
Hmm.. it's strange a bit.
It works in my app even on windows
and crashes only in your render_test

**Comment by igagis** [comment]
I think it fails only in debug build, because in release builds assertions are turned off

**Comment by Papirosnik** [comment]
it's not an assertion.
it crashes here:
ret.data.resize(src.width * src.height * sizeof(std::uint32_t));
...
 ret.surface.data = &*ret.data.begin();

but for some reason width and heights are zero

**Comment by igagis** [comment]
It crashes on assertion inside operator* wehn trying to dereference data.begin().
Sizes are zero due to SVG contents, as far as I understand. But I will make a fix for that, it is pretty clear now what happens.

**Comment by igagis** [comment]
**svgren** version **0.4.55** released, please update and try.

**Comment by Papirosnik** [comment]
it works like a charm!
Thank you
