### ISSUE TITLE
SVG images with clipPath is not rendered correctly

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#58]
The attached image FW-5_PM-1.zip is not rendered correctly by svgren.
Firefox renders everything correct.
There is a clipPath at line 123 and 139 which causes the Problem.
The image in file FW-5_PM-1-fine is exactly the same image without clipPath and renders as it should.

[FW-5_PM-1-fine.zip](https://github.com/igagis/svgren/files/2560949/FW-5_PM-1-fine.zip)

[FW-5_PM-1.zip](https://github.com/igagis/svgren/files/2560940/FW-5_PM-1.zip)

**Comment by igagis** [comment]
clipPath is not implemented yet. I will do it soon

**Comment by saeitsystems** [comment]
Thanks again for your quick help. 
We use Affinity Designer from serif to create and export our images.
Since the last versions clippath is used more often (not just when using contrains) when exporting to svg.
Unfortunately there is no option to **not** use clippath in the export.
It would be a great help if you implement clippath quite soon.

**Comment by saeitsystems** [comment]
Hi,
after some more investigation I think the problem is not the clippath.
The transitions ar made with images now:
<image id="_Image11" width="46px" height="33px" xlink:href="data:image/png;base64,
I think this is not supportet too?

**Comment by saeitsystems** [comment]
Hi Ivan,
I found out, it's all my fault.
I got the export options in Affinity Designer wrong. Unsupported feature were rendered as embedded images.
After changing to not rendering anything every thing looks fine again.
Do you want me to close this issue?

**Comment by igagis** [comment]
ok, good to know it works for you now!
But I think this issue still can be open, since it is about `clipPath` which is not implemented, and it would be good to have it implemented eventually :)
