### ISSUE TITLE
this svg file not rendered correctly

### ISSUE THREAD

**Issue by swigger** [igagis/svgren#59]
compared to what is rendered in google chrome, svgren renders the mouse too large.

[mouse.zip](https://github.com/igagis/svgren/files/2588856/mouse.zip)

<img width="452" alt="bug" src="https://user-images.githubusercontent.com/12627791/48615836-ec307900-e9cc-11e8-89a6-928dafac2ee1.png">

**Comment by igagis** [comment]
The problem was in parsing transformations in **svgdom** library.
Now it is fixed in **svgdom** version **0.3.21**
