### ISSUE TITLE
how to render an svgresult to a new window ?

### ISSUE THREAD

**Issue by goodyes** [igagis/svgren#63]
Hello, can you point in how to render, position (move position) and clear an svgreen result to a screen or new window ? under windows, Gdiplus.  So how to convert the pixels returned by svgren::render , std_vector uint32_t to an Image (microsoft mfc gdiplus)

Justr after the wiki says "After that one can use the rendered image data to display it on any physical display or whatever", how to ?

**Comment by igagis** [comment]
there is a project for Visual Studio, look for it in `msvs_solution` directory.
There is a test application there which draws an SVG image in the window.

**Comment by goodyes** [comment]
under msvs_solution, project libsvgreen, render.cpp error:
cannot open source file for includes: 
#include <utki/config.hpp>#include <utki/util.hpp>

under msvs_solution, project render_test, render_test.cpp error:

cannot open source file for includes: 
#include <svgdom/dom.hpp>#include <papki/FSFile.hpp>




    En jueves, 20 de diciembre de 2018 10:57:37 CET, Ivan Gagis <notifications@github.com> escribió:  
 
 
there is a project for Visual Studio, look for it in msvs_solution directory.
There is a test application there which draws an SVG image in the window.

**Comment by goodyes** [comment]
Also on trying to compile, unable to start program .. libsvgren.lib is not a valid win32 application

![image](https://user-images.githubusercontent.com/7475040/50283152-5073ac00-0455-11e9-8b31-d509caaaa621.png)

**Comment by goodyes** [comment]
chaging to debug x86 (from previous debug x64) also same error:

![image](https://user-images.githubusercontent.com/7475040/50283249-93358400-0455-11e9-8d92-e36ba115b884.png)

**Comment by igagis** [comment]
there are 2 projects in the solutiuon, you need to start `render_test` one, not `libsvgren`.
Right click `render_test` and select `set default startup project` or something like that, then try to run

**Comment by goodyes** [comment]
solved, thks

**Comment by goodyes** [comment]
Is there any way to fit the image on to window ? (width and height)

**Comment by saeitsystems** [comment]
Just set the desired with and height in render parameters
