### ISSUE TITLE
fit image (svg) in window, on render test project under msvs_solution

### ISSUE THREAD

**Issue by goodyes** [igagis/svgren#64]
Is there any way to fit the image on to window ? (width and height)

**Comment by igagis** [comment]
Try explicitly set the width and height of the resulting image:

```cpp
svgren::Parameters p;
p.widthRequest = 1024; //0 means use width from SVG document
p.heightRequest = 768; //0 means use height from SVG document
auto result = svgren::render(*dom, p);
```

**Comment by goodyes** [comment]
Done, thks, it works wellThe only downside is that to load the svg takes too much time. But rest is nice.
    En jueves, 20 de diciembre de 2018 15:47:58 CET, Ivan Gagis <notifications@github.com> escribió:  
 
 
Try explicitly set the width and height of the resulting image:
svgren::Parameters p;
p.widthRequest = 1024; //0 means use width from SVG document
p.heightRequest = 768; //0 means use height from SVG document
auto result = svgren::render(*dom, p);

**Comment by igagis** [comment]
well, you have to load it only once ;). Rendering also can be slow, but that's for complex SVGs
