### ISSUE TITLE
Crash in VS 2017 when loading SVG

### ISSUE THREAD

**Issue by JFreyberger** [igagis/svgren#65]
Hi,

I just created a minimal project in VS2017, added libsvgren via NuGet and tested your minimal example. Whenever I try to load any svg (tried various also from your examples) it crashes with access violation ("**_Parent_proxy**" was "0xCCCCCCCC". ) in xutility line 164:

 #if _ITERATOR_DEBUG_LEVEL == 2
			if (_Myproxy != _Parent_proxy)
				{	// change parentage
				_Lockit _Lock(_LOCK_DEBUG);
				_Orphan_me();
=>				_Mynextiter = _Parent_proxy->_Myfirstiter;
				_Parent_proxy->_Myfirstiter = this;
				_Myproxy = _Parent_proxy;
				}

The call stack looks like this:
>	MyLittleSvgTest.exe!std::_Iterator_base12::_Adopt(const std::_Container_base12 * _Parent) Zeile 164	C++
 	MyLittleSvgTest.exe!std::_Tree_unchecked_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > >,std::_Iterator_base12>::_Tree_unchecked_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > >,std::_Iterator_base12>(std::_Tree_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > >,void *> * _Pnode, const std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > * _Plist) Zeile 45	C++
 	MyLittleSvgTest.exe!std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > >::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > >(std::_Tree_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > >,void *> * _Pnode, const std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > * _Plist) Zeile 215	C++
 	MyLittleSvgTest.exe!std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > >::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > >(std::_Tree_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > >,void *> * _Pnode, const std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > > * _Plist) Zeile 328	C++
 	MyLittleSvgTest.exe!std::_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<char,std::allocator<char> >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > >,0> >::end() Zeile 1199	C++
 	MyLittleSvgTest.exe!std::_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<char,std::allocator<char> >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > >,0> >::_Tidy() Zeile 2113	C++
 	MyLittleSvgTest.exe!std::_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<char,std::allocator<char> >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > >,0> >::~_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<char,std::allocator<char> >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > >,0> >() Zeile 1169	C++
 	MyLittleSvgTest.exe!std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<char,std::allocator<char> >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > >::~map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<char,std::allocator<char> >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::vector<char,std::allocator<char> > > > >()	C++
 	MyLittleSvgTest.exe!mikroxml::Parser::~Parser() Zeile 146	C++
 	MyLittleSvgTest.exe!svgdom::Parser::~Parser()	C++
 	MyLittleSvgTest.exe!svgdom::load(const papki::File & f) Zeile 31	C++
 	MyLittleSvgTest.exe!main() Zeile 12	C++

here's my packages.config:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="cairo_static" version="1.15.4.2" targetFramework="native" />
  <package id="libmikroxml" version="0.1.1" targetFramework="native" />
  <package id="libpapki" version="1.0.26" targetFramework="native" />
  <package id="libpng_native" version="1.6.30" targetFramework="native" />
  <package id="libpng_native.redist" version="1.6.30" targetFramework="native" />
  <package id="libsvgdom" version="0.3.22" targetFramework="native" />
  <package id="libsvgren" version="0.4.57" targetFramework="native" />
  <package id="libunikod" version="2.0.17" targetFramework="native" />
  <package id="libutki" version="1.1.25" targetFramework="native" />
  <package id="pixman_static" version="0.32.4.5" targetFramework="native" />
  <package id="zlib_native" version="1.2.11" targetFramework="native" />
  <package id="zlib_native.redist" version="1.2.11" targetFramework="native" />
</packages>

Probably I'm just missing some compiler option etc. but I don't know which. Do you have any ideas?

Thanks and best regards,
Johannes

**Comment by JFreyberger** [comment]
... sorry. I didn't update to the latest libraries. Now there's no crash anymore :-)

**Comment by igagis** [comment]
Great!
