### ISSUE TITLE
Wrong SVG rendering

### ISSUE THREAD

**Issue by lucdion** [igagis/svgren#66]
Hi, the following SVG rendering is not right. It should be a white "6" number inside a black circle.

Result:
<img width="52" alt="image" src="https://user-images.githubusercontent.com/14981341/64354280-25be8900-cfcd-11e9-9907-c32572f973b8.png">

Expected Result:
<img width="52" alt="image" src="https://user-images.githubusercontent.com/14981341/64354317-3a9b1c80-cfcd-11e9-9756-52420fb8a211.png">

SVG in GIMP:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/14981341/64354344-4686de80-cfcd-11e9-8f7d-94221bfe03c1.png">

[color.svg.zip](https://github.com/igagis/svgren/files/3579851/color.svg.zip)

Thanks

**Comment by igagis** [comment]
Thanks for reporting the bug!
Is this sample SVG generated by some program or is it handwritten?

I found that it specifies arc in path and it combines 3 of its parameters which are `large-arc-flag`, `sweep-flag`, `x` to a string `100`, so it is `large-arc-flag=1`, `sweep-flag=0`, `x=0` and **svgdom** parser does not like that, it expects spaces between the numbers, like `1 0 0`. It does not look like it is according to the svg spec, but for example Firefox renders the image correctly. So I'll try to fix it in **svgdom** as well.

**Comment by igagis** [comment]
The bug is fixed in **svgdom** version `0.3.25`.
Please test and close the bug.

**Comment by lucdion** [comment]
Thanks for the quick fix!
The file has been generated using SVG optimize.
