### ISSUE TITLE
Red and blue color components are inverted

### ISSUE THREAD

**Issue by lucdion** [igagis/svgren#67]
Hi, using the latest release, the following image should be rendered red, but it is blue.

Result:
<img width="58" alt="image" src="https://user-images.githubusercontent.com/14981341/64639977-05306d80-d3d7-11e9-9041-a664e93b4110.png">

Expected result:
<img width="137" alt="image" src="https://user-images.githubusercontent.com/14981341/64639932-ed58e980-d3d6-11e9-9dca-b8b86262d214.png">

[-3color.svg.zip](https://github.com/igagis/svgren/files/3597203/-3color.svg.zip)

**Comment by igagis** [comment]
Was it normal with previous release?

**Comment by igagis** [comment]
I have just tested it in linux with latest **svgren** and it draws red circle. Which system are you running it on?

**Comment by lucdion** [comment]
Or you're right @igagis, `bgra` was set to `true`. My mistake, sorry
