### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by lucdion** [igagis/svgren#68]
Hi, the rendering of this SVG is different using svgren compared to Gimp results. The "R" in the center is missing.

Result:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/14981341/64646359-f0f36d00-d3e4-11e9-9c97-2f569e439ecf.png">

Expected Result:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/14981341/64646373-fc469880-d3e4-11e9-9a2e-8c8af01c15fe.png">

[-3.svg.zip](https://github.com/igagis/svgren/files/3597500/-3.svg.zip)

**Comment by igagis** [comment]
It might be that you are using black background for that image. The "R" is not white, it is transparent. In GIMP you probably applied white background layer while in your app you probably have black background. Could you check?

**Comment by lucdion** [comment]
You're right, the "R" is transparent. If I put a yellowish background, here is the result

<img width="43" alt="image" src="https://user-images.githubusercontent.com/14981341/64647714-83950b80-d3e7-11e9-845d-f42d6aaab0a7.png">

**Comment by igagis** [comment]
Strange, I checked on my end, it works correctly on linux. On what system do run it?

**Comment by lucdion** [comment]
iOS

**Comment by lucdion** [comment]
Oh, my mistake (again) 😬 Sorry for this. 
By the way, your lib is amazing! Really good job.

**Comment by igagis** [comment]
Ok, no problem!
