### ISSUE TITLE
Runtime Library Multi thread

### ISSUE THREAD

**Issue by SlavaSharunov** [igagis/svgren#69]
Hello Ivan,

Would it be possible for you to recompile the libraries under VS2019 and Multi-threaded Runtime Library? The whole our project is compiled as multi threaded and all extern libraries for it need to be as well compiled as /MT...
May I ask you for a favor to do it? Support of VS2019 (v142) would be appreciated as well.

Thank you in advance

**Comment by igagis** [comment]
**svgren** is currently compiled for Multi-threaded runtime, but for DLL version of it (`/MD`). What is the reasoning behind you are using static runtime linking in your project?

I need to check if it is possible to support both configurations in a single NuGet package.

**Comment by SlavaSharunov** [comment]
Hi Ivan,

Our project is very old and multimodular, so what was a reason  - I dont know and nobody can find an answer now. Recompile as MD is unfortunatelly not the solution.

**Comment by igagis** [comment]
Ok, I'll investigate more about how to proceed. And I will definitely add `v142` support.

**Comment by igagis** [comment]
blocked by this: https://help.appveyor.com/discussions/problems/25042-appveyor-executor-crashes

**Comment by igagis** [comment]
now blocked by this https://help.appveyor.com/discussions/problems/25054-v140-and-v141-build-tools-are-missing-from-visual-studio-2019-image

**Comment by igagis** [comment]
blocked by:
https://github.com/appveyor/ci/issues/3071
https://github.com/appveyor/ci/issues/3113
https://github.com/appveyor/ci/issues/3114

**Comment by igagis** [comment]
@SlavaSharunov are you sure that `MT/MD` options make sense for static libraries?
My understanding is that `MT/MD` option of the final application is taken into use and all static libs the app links will be linked to that `MT` or `MD` as defined by the application project.

**Comment by igagis** [comment]
Ok, never mind. I have tested and it looks like it is needed.

**Comment by igagis** [comment]
The new version of nuget package is now available. **libsvgren** version **0.4.59**, please update all your nuget packages.

It now supports `v142` tools and also `MT/MTd/MD/MDd`. When using `v142` tools you have to set the `Runtime Library` option in project `properties/Project Master Settings`.

Please verify and close the bug if it works.

**Comment by SlavaSharunov** [comment]
Hi Ivan, 
Thank you. Now it compiles without any errors.

I close the issue.
Have a nice day.
