### ISSUE TITLE
Drawing problem

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#7]
I have a drawing problem with svgren. The Lines are missing.

This is the output of svgren:
![symboldrawproblem](https://cloud.githubusercontent.com/assets/25054917/21981177/7aa55076-dbe6-11e6-9341-0abde80f1115.png)

And this is the way it is supposed to look (like firefox renders it):
![correctsymbol](https://cloud.githubusercontent.com/assets/25054917/21981197/8af4c592-dbe6-11e6-84cc-e60689dfea68.png)

This is the korosponding SVG file:
[interface-ethernet.zip](https://github.com/igagis/svgren/files/708160/interface-ethernet.zip)

I hope you can fix this problem.

**Comment by igagis** [comment]
I can't reproduce the problem so far, here is the result I get:
![screenshot_2017-01-16_13-34-51](https://cloud.githubusercontent.com/assets/783401/21981539/9ab6c6ce-dbf0-11e6-85cf-4446cbeee15d.png)

On your screenshot I see that the arrow lines are still rendered but with some wrong transformation, those are smaller than those should be. Could you check if there are any specifics in your code how you render those, like what are the input width and height and what are the dpi, or maybe something else, like do you modify DOM anyhow before rendering?

**Comment by igagis** [comment]
Ok, I reproduced it on Windows, on Linux it works fine. Probably on windows older version of cairo is used... I will try to investigate

**Comment by igagis** [comment]
Bug is fixed. Please update **libsvgdom** to version 0.2.25

**Comment by saeitsystems** [comment]
**Thank you! The problem has been resolved with your fix!**

I wonder why you are using real instead of double in your libsvgdom. As far as I know double doesn't slow down the process because double is supported by the coprocessor. On some systems double is even faster then real because of that. And the required space for double is less importand since available memory has been increased in the past a lot.

**Comment by igagis** [comment]
Single precision float is enough for SVG and then why spend twice as more memory if it is not needed at all. Anyway, one can recompile it with different typedef for real if needed. But it works now, so no need to be concerned :)

**Comment by saeitsystems** [comment]
It was just a question ... If SVG / cairo don't need/support more precision everything is fine and your bugfix was the correct solution if the numbers beyond real are allowed in the SVG file.
