### ISSUE TITLE
VS2019 link error

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#71]
Hello,

I use svgren with VS2017 and want to move to VS2019. Everything compiles fine now but at the end I get several link errors. These errors seem to be caused by microxml, svgdom and svgren.

`
   Creating library .\Setit\debug\setIT V6.lib and object .\Setit\debug\setIT V6.exp
cUpdateInfoParser.obj : error LNK2019: unresolved external symbol "public: __thiscall mikroxml::Parser::Parser(void)" (??0Parser@mikroxml@@QAE@XZ) referenced in function "public: __thiscall cUpdateInfoParser::cUpdateInfoParser(struct sUpdateEntry &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class ATL::CStringT<char,class StrTraitMFC_DLL<char,class ATL::ChTraitsCRT<char> > >,class std::allocator<class ATL::CStringT<char,class StrTraitMFC_DLL<char,class ATL::ChTraitsCRT<char> > > > > const &)" (??0cUpdateInfoParser@@QAE@AAUsUpdateEntry@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$vector@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@V?$allocator@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@std@@@3@@Z)
cUpdateInfoParser.obj : error LNK2019: unresolved external symbol "public: void __thiscall mikroxml::Parser::feed(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?feed@Parser@mikroxml@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: __thiscall cUpdateInfoParser::cUpdateInfoParser(struct sUpdateEntry &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class ATL::CStringT<char,class StrTraitMFC_DLL<char,class ATL::ChTraitsCRT<char> > >,class std::allocator<class ATL::CStringT<char,class StrTraitMFC_DLL<char,class ATL::ChTraitsCRT<char> > > > > const &)" (??0cUpdateInfoParser@@QAE@AAUsUpdateEntry@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$vector@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@V?$allocator@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@std@@@3@@Z)
CxImageSVG.obj : error LNK2019: unresolved external symbol "public: float __thiscall svgdom::Length::toPx(float)const " (?toPx@Length@svgdom@@QBEMM@Z) referenced in function "private: void __thiscall cSVGimage::Dimensions(unsigned int &,unsigned int &)const " (?Dimensions@cSVGimage@@ABEXAAI0@Z)
CxImageSVG.obj : error LNK2019: unresolved external symbol "class std::unique_ptr<struct svgdom::SvgElement,struct std::default_delete<struct svgdom::SvgElement> > __cdecl svgdom::load(class utki::Buf<char>)" (?load@svgdom@@YA?AV?$unique_ptr@USvgElement@svgdom@@U?$default_delete@USvgElement@svgdom@@@std@@@std@@V?$Buf@D@utki@@@Z) referenced in function "public: __thiscall cSVGimage::cSVGimage(class ATL::CStringT<wchar_t,class StrTraitMFC_DLL<wchar_t,class ATL::ChTraitsCRT<wchar_t> > > const &)" (??0cSVGimage@@QAE@ABV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z)
CxImageSVG.obj : error LNK2019: unresolved external symbol "struct svgren::Result __cdecl svgren::render(struct svgdom::SvgElement const &,struct svgren::Parameters const &)" (?render@svgren@@YA?AUResult@1@ABUSvgElement@svgdom@@ABUParameters@1@@Z) referenced in function "private: void __thiscall cSVGimage::Dimensions(unsigned int &,unsigned int &)const " (?Dimensions@cSVGimage@@ABEXAAI0@Z)
.\Setit\debug\setIT V6.exe : fatal error LNK1120: 5 unresolved externals
Done building project "Setit.vcxproj" -- FAILED.
`
These funktions are unresolved:
**error LNK2019: unresolved external symbol "public: __thiscall mikroxml::Parser::Parser
error LNK2019: unresolved external symbol "public: void __thiscall mikroxml::Parser::feed
error LNK2019: unresolved external symbol "public: float __thiscall svgdom::Length::toPx
error LNK2019: unresolved external symbol "class std::unique_ptr<struct svgdom::SvgElement,struct std::default_delete<struct svgdom::SvgElement> > __cdecl svgdom::load
error LNK2019: unresolved external symbol "struct svgren::Result __cdecl svgren::render**

I have attached the VS2019 settings as screenshot. All NuGet packages are up to date.
I hope you can help.
![VS2019-settings](https://user-images.githubusercontent.com/25054917/72242465-d2e38680-35e9-11ea-9970-92692b07b2a9.png)

**Comment by igagis** [comment]
I have just updated the installation instructions with some info about VS2019, see here:
https://github.com/igagis/svgren/blob/master/wiki/InstallMSVS.md

Probably you did not configure that setting, please try that.

**Comment by saeitsystems** [comment]
Thank you very much for your quick help! That fixed our Problem.

**Comment by igagis** [comment]
You're welcome :)
