### ISSUE TITLE
Text element not suported

### ISSUE THREAD

**Issue by spger** [igagis/svgren#76]
Hi, I upload some svg images and is not possible represent text element. Example:
<text x="776.777" y="235.223" fill="rgb(255,0,0)" font-size="10" font-family="Verdana" >20 Sec</text>
 Is possible get it?
thanks

**Comment by igagis** [comment]
Hi, `text` element is not supported and is not planned to be supported, as said here https://github.com/igagis/svgren/blob/master/wiki/Features.adoc

**Comment by igagis** [comment]
The workaround is to convert all text to paths in some SVG editor, for example Inkscape, save the SVG after that in use that SVG.
