### ISSUE TITLE
Sinve the new version transparency is gone

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#8]
Hi,
I just wanted to update all the libraries to the latest version .... 
Transparency seems to be gone ....
![2017-03-01 15_08_45-clipboard](https://cloud.githubusercontent.com/assets/25054917/23463432/c327d364-fe91-11e6-9c50-9373c741f820.jpg)

I think I need to stay on the "old" version until this is fixed.

After some investigation I thing it is your change: "msvs: define white background macro for debug builds "
In my case I need transparency in DEBUG as well.

Why not just passing the desired background colour as a parameter with default zero?

**Comment by igagis** [comment]
Right, I will fix it today evening. Probably need to create another build configuration for development purposes.

**Comment by saeitsystems** [comment]
Thanks! The deployed libraries should both, debug and release, generate the same output.

**Comment by igagis** [comment]
Please try *svgren* version 0.4.7

**Comment by saeitsystems** [comment]
Thanks, version 0.4.7 fixed the problem!
