### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by liushui123456** [igagis/svgren#80]
Why the background color is black

**Comment by liushui123456** [comment]
@igagis

**Comment by igagis** [comment]
The background color is _transparent_ black. I.e. after rendering the svg one can blend it to any background they want.

**Comment by liushui123456** [comment]
how can i get the white black

**Comment by igagis** [comment]
white black?

**Comment by liushui123456** [comment]
![white_back](https://user-images.githubusercontent.com/44079926/97865004-756d2180-1d44-11eb-8a0e-49726a3aaf75.jpg)
![back_background](https://user-images.githubusercontent.com/44079926/97865295-f2000000-1d44-11eb-9a12-3a8c4aedbe6f.jpg)

like this ，I dont want black background

**Comment by liushui123456** [comment]
how can i get the first image

**Comment by igagis** [comment]
Either make your SVG file contain the white background, or, after rendering the image you can blend in the white color by hand to each pixel. If you don't know how to do that, you can read about that for example here: https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending

**Comment by liushui123456** [comment]
Thank you for taking the time to answer my question

**Comment by igagis** [comment]
you are welcome!
