### ISSUE TITLE
I can't link the release version after update to the new svgren version 

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgren#81]
Hi,
after the update to the new version I had to change some parameter names (why is the bgra option removed).
The debug version runs fine and at the first view I couldn't find any differences to the cairo based version.
With linking the relase version of our software I get this error:

`
LINK : fatal error C1047: The object or library file 'K:\sae\nfs\software\packages\zlib_static.1.2.11.5\build\native\..\..\\build\native\lib\Win32\v142\Release\MultiThreadedDLL\zlib.lib' was created by a different version of the compiler than other objects like 'K:\sae\nfs\software\packages\libcssdom.0.1.10\build\native\..\..\\build\native\lib\Win32\v142\Release\MultiThreadedDLL\libcssdom.lib'; rebuild all objects and libraries with the same compiler
`
Please help to get this fixed. Otherwise I have to revert to the old version of svgren.

Thanks!

**Comment by igagis** [comment]
Looks like I need to rebuild the `zlib_static` nuget package with updated SDK version, will do this today evening.

The BGRA option was removed because it seems like it is out of the API's scope.
If you need to convert to BGRA image this can easily be done as follows:
````
auto res = svgren::render(*dom, params);

// swap red and blue channels
for(auto& c : res.pixels){
    c = (c & 0xff00ff00) | ((c << 16) & 0xff0000) | ((c >> 16) & 0xff);
}
````

**Comment by saeitsystems** [comment]
Ok, I remember that this is what you did inside of render and to save a double swap you introduced the BGRA option.
I already do the swap right now.
Would be great to solve the link problem. I use version 16.8.2 from VS2019.

**Comment by igagis** [comment]
I have rebuilt the `zlib_static` and `libpapki` packages against latest SDK version. Please update your packages and try again.

New package versions:
`zlib_static`: **1.2.11.6**
`libpapki`: **1.0.85**

The rest of the packages are already built against latest SDK.

Let me know if it helps or not.

I could not reproduce exact your problem, but I could reproduce something very similar with my project, and unfortunately, rebuilding those packages did not solve it. I will continue investigation.

**Comment by saeitsystems** [comment]
Hi Ivan,
thank you very much for your great support. Your changes worked for me, everything looks fine now! 
I can swap to the new agg based library now.

**Comment by igagis** [comment]
That's great that it worked for you! Thanks for reporting the problem!

**Comment by saeitsystems** [comment]
Just for information, I got this message on a VS2019 Installation with 16.7.7 Version on ist:
  
```
LINK : fatal error C1900: Il mismatch between 'P1' version '20200803' and 'P2' version '20190715' [E:\sae\nfs\jenkins\trunk\software\workspace\Setit.vcxproj]
  LINK : fatal error LNK1257: code generation failed [E:\sae\nfs\jenkins\trunk\software\workspace\Setit.vcxproj]
```
After updation to the actual version 16.8.2 everything linked fine
