### ISSUE TITLE
Strange rendering of path element

### ISSUE THREAD

**Issue by skalleAnka** [igagis/svgren#9]
I am adding SVG support to a little hobby game I have. I made a test picture with Inkscape and tried to load it. Here are the results:
![real](https://cloud.githubusercontent.com/assets/26508773/24074574/b0601642-0c0b-11e7-8e19-b462340f0e65.png)
![render](https://cloud.githubusercontent.com/assets/26508773/24074576/b60d934e-0c0b-11e7-835f-8aaa66785f01.png)

The body of the character in the in-game screenshot is rendered as a triangle. Here is the SVG file used:
[test.zip](https://github.com/igagis/svgren/files/852628/test.zip)

I it matters I am using 64 bit Windows 7, the latest svgren from GIT, libsvgdom.0.2.25 and cairo_static.1.15.4.1.

And also, a big thank you for making this library.

**Comment by igagis** [comment]
Thanks for reporting this, It is now fixed. Please update to **libsvgren** version 0.4.8 and try.

**Comment by skalleAnka** [comment]
Wow that was fast. Very impressive. It works now!
